services:
  mysql:
    image: mysql:8.0
    container_name: eventzen-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventzen
      MYSQL_USER: eventzen_user
      MYSQL_PASSWORD: eventzen_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  backend:
    build:
      context: ./eventzen-backend
      dockerfile: Dockerfile
    container_name: eventzen-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventzen?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectionTimeout=30000&socketTimeout=30000
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  frontend:
    build:
      context: ./eventzen-frontend
      dockerfile: Dockerfile
    container_name: eventzen-frontend
    ports:
      - "5000:5000"
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: